import { Component, Input } from '@angular/core';
import { SharedDataService } from '../../services/shared-data.service';

@Component({
  selector: 'app-page4',
  templateUrl: './page4.component.html',
  styleUrl: './page4.component.css'
})
export class Page4Component {
  @Input() terapeut!: string;

  nume: string = "";
  specializare: string = "";
  despreMine: string = "";
  email: string = "";
  telefon: string = "0723 456 789";

  datePersoana: { [key: string]: { specializari: string[]; email: string; telefon: string } } = {
  'Paul M. Lehrer': {'specializari': ['Terapia prin biofeedback'],
  'email': 'paul.m..lehrer@therapyexample.com',
  'telefon': '0770637469'},
 'Laura A. Smith': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'laura.a..smith@therapyexample.com',
  'telefon': '0770267437'},
 'Michael J. Anderson': {'specializari': ['Terapia psihodinamică'],
  'email': 'michael.j..anderson@therapyexample.com',
  'telefon': '0770725417'},
 'Sarah E. Johnson': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'sarah.e..johnson@therapyexample.com',
  'telefon': '0770514095'},
 'David M. Rodriguez': {'specializari': ['Terapia de grup'],
  'email': 'david.m..rodriguez@therapyexample.com',
  'telefon': '0770809263'},
 'Emily K. Williams': {'specializari': ['Terapia cognitivă'],
  'email': 'emily.k..williams@therapyexample.com',
  'telefon': '0770824264'},
 'John R. Thompson': {'specializari': ['Terapia de relaxare'],
  'email': 'john.r..thompson@therapyexample.com',
  'telefon': '0770861381'},
 'Jessica L. Davis': {'specializari': ['Terapia prin joc de rol'],
  'email': 'jessica.l..davis@therapyexample.com',
  'telefon': '0770989413'},
 'Brian A. Martinez': {'specializari': ['Terapia prin expunere virtuală'],
  'email': 'brian.a..martinez@therapyexample.com',
  'telefon': '0770672031'},
 'Rachel S. Clark': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'rachel.s..clark@therapyexample.com',
  'telefon': '0770731559'},
 'Anna R. Lewis': {'specializari': ['Terapia prin biofeedback'],
  'email': 'anna.r..lewis@therapyexample.com',
  'telefon': '0770351919'},
 'Robert M. Walker': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'robert.m..walker@therapyexample.com',
  'telefon': '0770376874'},
 'Julia E. Anderson': {'specializari': ['Terapia psihodinamică'],
  'email': 'julia.e..anderson@therapyexample.com',
  'telefon': '0770147988'},
 'Daniel S. Taylor': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'daniel.s..taylor@therapyexample.com',
  'telefon': '0770086870'},
 'Sophie L. Martinez': {'specializari': ['Terapia de grup'],
  'email': 'sophie.l..martinez@therapyexample.com',
  'telefon': '0770772072'},
 'David A. Rodriguez': {'specializari': ['Terapia cognitivă'],
  'email': 'david.a..rodriguez@therapyexample.com',
  'telefon': '0770204969'},
 'Emily K. Thompson': {'specializari': ['Terapia de relaxare'],
  'email': 'emily.k..thompson@therapyexample.com',
  'telefon': '0770868710'},
 'John R. Davis': {'specializari': ['Terapia prin joc de rol'],
  'email': 'john.r..davis@therapyexample.com',
  'telefon': '0770667427'},
 'Jessica S. Martinez': {'specializari': ['Terapia prin expunere virtuală'],
  'email': 'jessica.s..martinez@therapyexample.com',
  'telefon': '0770520242'},
 'Brian A. Clark': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'brian.a..clark@therapyexample.com',
  'telefon': '0770049668'},
 'Liam M. Williams': {'specializari': ['Terapia prin biofeedback'],
  'email': 'liam.m..williams@therapyexample.com',
  'telefon': '0770992603'},
 'Olivia R. Anderson': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'olivia.r..anderson@therapyexample.com',
  'telefon': '0770346636'},
 'Ethan S. Taylor': {'specializari': ['Terapia psihodinamică'],
  'email': 'ethan.s..taylor@therapyexample.com',
  'telefon': '0770251984'},
 'Ava J. Rodriguez': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'ava.j..rodriguez@therapyexample.com',
  'telefon': '0770539686'},
 'Noah A. Martinez': {'specializari': ['Terapia de grup'],
  'email': 'noah.a..martinez@therapyexample.com',
  'telefon': '0770008838'},
 'Sophia E. Thompson': {'specializari': ['Terapia cognitivă'],
  'email': 'sophia.e..thompson@therapyexample.com',
  'telefon': '0770265784'},
 'Logan R. Davis': {'specializari': ['Terapia de relaxare',
   'Terapia prin joc de rol',
   'Terapia prin biofeedback'],
  'email': 'logan.r..davis@therapyexample.com',
  'telefon': '0770029757'},
 'Isabella S. Martinez': {'specializari': ['Terapia prin joc de rol'],
  'email': 'isabella.s..martinez@therapyexample.com',
  'telefon': '0770830093'},
 'Jackson A. Clark': {'specializari': ['Terapia prin expunere virtuală'],
  'email': 'jackson.a..clark@therapyexample.com',
  'telefon': '0770612040'},
 'Nora R. Williams': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'nora.r..williams@therapyexample.com',
  'telefon': '0770700115'},
 'Alex M. Johnson': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'alex.m..johnson@therapyexample.com',
  'telefon': '0770640021'},
 'Emma R. Davis': {'specializari': ['Terapia prin expunere'],
  'email': 'emma.r..davis@therapyexample.com',
  'telefon': '0770495636'},
 'Daniel L. Smith': {'specializari': ['Terapia cognitivă'],
  'email': 'daniel.l..smith@therapyexample.com',
  'telefon': '0770705743'},
 'Sophia K. Turner': {'specializari': ['Terapia de grup'],
  'email': 'sophia.k..turner@therapyexample.com',
  'telefon': '0770155085'},
 'Nathan A. Anderson': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'nathan.a..anderson@therapyexample.com',
  'telefon': '0770233292'},
 'Lily R. Martinez': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'lily.r..martinez@therapyexample.com',
  'telefon': '0770236380'},
 'Owen K. Thompson': {'specializari': ['Terapia cognitivă bazată pe conștientizare (MBCT)'],
  'email': 'owen.k..thompson@therapyexample.com',
  'telefon': '0770761708'},
 'Emily S. Clark': {'specializari': ['Terapia de expunere virtuală'],
  'email': 'emily.s..clark@therapyexample.com',
  'telefon': '0770816926'},
 'Ava J. Anderson': {'specializari': ['Terapia prin biofeedback',
   'Terapia de relaxare',
   'Terapia cognitivă analitică (TCA)'],
  'email': 'ava.j..anderson@therapyexample.com',
  'telefon': '0770983010'},
 'Aiden M. Johnson': {'specializari': ['Terapia cognitiv-comportamentală (TCC)',
   'Terapia dialectică comportamentală (DBT)'],
  'email': 'aiden.m..johnson@therapyexample.com',
  'telefon': '0770446882'},
 'Sophia L. Anderson': {'specializari': ['Terapia dialectică comportamentală (DBT)',
   'Terapia cognitiv-comportamentală (TCC)'],
  'email': 'sophia.l..anderson@therapyexample.com',
  'telefon': '0770223757'},
 'Nathan L. Smith': {'specializari': ['Terapia cognitivă',
   'Terapia prin acceptare și angajament (ACT)'],
  'email': 'nathan.l..smith@therapyexample.com',
  'telefon': '0770073073'},
 'Emma K. Turner': {'specializari': ['Terapia de grup'],
  'email': 'emma.k..turner@therapyexample.com',
  'telefon': '0770573282'},
 'Liam A. Anderson': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'liam.a..anderson@therapyexample.com',
  'telefon': '0770811152'},
 'Ava R. Martinez': {'specializari': ['Terapia prin acceptare și angajament (ACT)',
   'Terapia de expunere virtuală'],
  'email': 'ava.r..martinez@therapyexample.com',
  'telefon': '0770830304'},
 'Lily S. Clark': {'specializari': ['Terapia de expunere virtuală',
   'Terapia prin joc de rol'],
  'email': 'lily.s..clark@therapyexample.com',
  'telefon': '0770377620'},
 'Eva M. Johnson': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'eva.m..johnson@therapyexample.com',
  'telefon': '0770025655'},
 'Noah L. Anderson': {'specializari': ['Terapia dialectică comportamentală (DBT)'],
  'email': 'noah.l..anderson@therapyexample.com',
  'telefon': '0770525714'},
 'Sophia R. Smith': {'specializari': ['Terapia cognitivă'],
  'email': 'sophia.r..smith@therapyexample.com',
  'telefon': '0770004232'},
 'Nathan K. Turner': {'specializari': ['Terapia de grup'],
  'email': 'nathan.k..turner@therapyexample.com',
  'telefon': '0770004528'},
 'Emma A. Anderson': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'emma.a..anderson@therapyexample.com',
  'telefon': '0770470420'},
 'Liam R. Martinez': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'liam.r..martinez@therapyexample.com',
  'telefon': '0770346021'},
 'Ava K. Thompson': {'specializari': ['Terapia cognitivă bazată pe conștientizare (MBCT)'],
  'email': 'ava.k..thompson@therapyexample.com',
  'telefon': '0770895927'},
 'Owen S. Clark': {'specializari': ['Terapia de expunere virtuală'],
  'email': 'owen.s..clark@therapyexample.com',
  'telefon': '0770715619'},
 'Lily J. Davis': {'specializari': ['Terapia prin joc de rol'],
  'email': 'lily.j..davis@therapyexample.com',
  'telefon': '0770190708'},
 'Logan R. Anderson': {'specializari': ['Terapia prin biofeedback'],
  'email': 'logan.r..anderson@therapyexample.com',
  'telefon': '0770569692'},
 'Sophie M. Johnson': {'specializari': ['Terapia cognitiv-comportamentală (TCC)'],
  'email': 'sophie.m..johnson@therapyexample.com',
  'telefon': '0770187968'},
 'Nathan L. Anderson': {'specializari': ['Terapia dialectică comportamentală (DBT)'],
  'email': 'nathan.l..anderson@therapyexample.com',
  'telefon': '0770330726'},
 'Emma R. Smith': {'specializari': ['Terapia cognitivă'],
  'email': 'emma.r..smith@therapyexample.com',
  'telefon': '0770116528'},
 'Logan K. Turner': {'specializari': ['Terapia de grup',
   'Terapia prin biofeedback'],
  'email': 'logan.k..turner@therapyexample.com',
  'telefon': '0770959950'},
 'Ava A. Anderson': {'specializari': ['Terapia cognitivă analitică (TCA)'],
  'email': 'ava.a..anderson@therapyexample.com',
  'telefon': '0770395540'},
 'Olivia A. Miller': {'specializari': ['Terapia cognitiv-comportamentală (TCC)',
   'Terapia cognit-comportamentală (TCC)'],
  'email': 'olivia.a..miller@therapyexample.com',
  'telefon': '0770744635'},
 'Ethan R. Martinez': {'specializari': ['Terapia dialectică comportamentală (DBT)'],
  'email': 'ethan.r..martinez@therapyexample.com',
  'telefon': '0770326731'},
 'Natalie S. Clark': {'specializari': ['Terapia cognitivă'],
  'email': 'natalie.s..clark@therapyexample.com',
  'telefon': '0770920729'},
 'Eli K. Turner': {'specializari': ['Terapia de grup'],
  'email': 'eli.k..turner@therapyexample.com',
  'telefon': '0770694946'},
 'Mason L. Thompson': {'specializari': ['Terapia prin acceptare și angajament (ACT)'],
  'email': 'mason.l..thompson@therapyexample.com',
  'telefon': '0770840990'},
 'Zoe K. Clark': {'specializari': ['Terapia cognitivă bazată pe conștientizare (MBCT)'],
  'email': 'zoe.k..clark@therapyexample.com',
  'telefon': '0770158740'},
 'Benjamin S. Davis': {'specializari': ['Terapia de expunere virtuală'],
  'email': 'benjamin.s..davis@therapyexample.com',
  'telefon': '0770645629'},
 'Lily M. Anderson': {'specializari': ['Terapia prin joc de rol'],
  'email': 'lily.m..anderson@therapyexample.com',
  'telefon': '0770245840'}}
    
  constructor(private sharedDataService: SharedDataService) { }

  ngOnInit() {
    this.nume = this.terapeut;
    this.specializare = this.datePersoana[this.terapeut].specializari.join(", ");
    this.email = this.datePersoana[this.terapeut].email;
    this.telefon = this.datePersoana[this.terapeut].telefon;
  }


}
